[participants.0]
output_column_names = [ "Year", "Wealth", "Total Wealth", "Rank" ]
[participants.1]
output_column_names = [ "Year", "Wealth", "Total Wealth", "Rank" ]
[participants.2]
output_column_names = [ "Year", "Wealth", "Total Wealth", "Rank" ]
